require 'rest-client'
url ="http://localhost:3000/users"
puts RestClient.get(url)
puts "-------------------------"
puts RestClient.get("http://localhost:3000/users/new")
puts "-------------------------"
puts RestClient.get("http://localhost:3000/users/:id")
puts "-----------------------"
puts RestClient.get("http://localhost:3000/users/:id/edit")